/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pp;

import com.pp.bom.Address;
import com.pp.bom.TollParking;
import com.pp.bom.pricingPolicy.ParkingRate;

import java.util.HashMap;
import java.util.Map;

import com.pp.bom.*;

public class App {

    public static void main(String[] args) {
    	

    
    }
}
